version: '3.7'

services:
  web:
    build:
      context: ./
      target: debug
      args:
        STATIC_URL: '/static/'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - 8000:8000  # django
      - 5678:5678  # debuger's port
  db:
    image: postgres:12.0-alpine
    volumes:
      - dm_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_DB=django_movie_dev

  redis:
    image: library/redis:5.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - dj_project-redis:/data

  worker:
    build:
      context: ./
      target: debug
      args:
        STATIC_URL: '/static/'
    command: celery --app=dj_project worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app

  flower:
    image: mher/flower:0.9.7
    command: flower --address=0.0.0.0 --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    restart: unless-stopped
volumes:
  dm_postgres_data:
  dj_project-redis: